# These are supported funding model platforms
# FUNDING.yml for TUFURE OS: AETHER CHAIN
# Support the development of a revolutionary decentralized operating system
# with blockchain integration, zero-knowledge privacy, and user-owned data economics.

custom: 
  - https://www.tufure.com
  - monero:8BZ3dYDRbsUCg73Ab7PMZQUinQpBuQSVWBcCAjSf4puVYKLfmEDBBfjdQXAnspE8dpJb9vgf8CrNGg8Cmt6HQDrB8SxtS9t
